name: lint check

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Lint check
        run: npm run lint

      - name: Run Prettier
        run: npx prettier --check 'src/**/*.{js,jsx,ts,tsx,json,css,scss,md}'
